#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ocl-icd
Version  : 2.2.12
Release  : 12
URL      : https://github.com/OCL-dev/ocl-icd/archive/v2.2.12/ocl-icd-2.2.12.tar.gz
Source0  : https://github.com/OCL-dev/ocl-icd/archive/v2.2.12/ocl-icd-2.2.12.tar.gz
Summary  : OpenCL ICD Bindings
Group    : Development/Tools
License  : BSD-2-Clause
Requires: ocl-icd-lib = %{version}-%{release}
Requires: ocl-icd-license = %{version}-%{release}
BuildRequires : ruby

%description
This package aims at creating an Open Source alternative to vendor specific
OpenCL ICD loaders.

%package dev
Summary: dev components for the ocl-icd package.
Group: Development
Requires: ocl-icd-lib = %{version}-%{release}
Provides: ocl-icd-devel = %{version}-%{release}
Requires: ocl-icd = %{version}-%{release}
Requires: ocl-icd = %{version}-%{release}

%description dev
dev components for the ocl-icd package.


%package doc
Summary: doc components for the ocl-icd package.
Group: Documentation

%description doc
doc components for the ocl-icd package.


%package lib
Summary: lib components for the ocl-icd package.
Group: Libraries
Requires: ocl-icd-license = %{version}-%{release}

%description lib
lib components for the ocl-icd package.


%package license
Summary: license components for the ocl-icd package.
Group: Default

%description license
license components for the ocl-icd package.


%prep
%setup -q -n ocl-icd-2.2.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560190293
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%reconfigure --disable-static --enable-custom-vendordir=/usr/share/OpenCL/vendors
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1560190293
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ocl-icd
cp COPYING %{buildroot}/usr/share/package-licenses/ocl-icd/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libOpenCL.so
/usr/lib64/pkgconfig/OpenCL.pc
/usr/lib64/pkgconfig/ocl-icd.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/ocl\-icd/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libOpenCL.so.1
/usr/lib64/libOpenCL.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ocl-icd/COPYING
